orb-community/orb-helm

charts/orb/Chart.yaml
charts/orb/templates/adapter_mqtt-statefulstet.yaml
charts/orb/templates/auth-deployment.yaml
charts/orb/templates/fleet-deployment.yaml
charts/orb/templates/policies-deployment.yaml
charts/orb/templates/sinker-deployment.yaml
charts/orb/templates/sinks-deployment.yaml
charts/orb/templates/things-deployment.yaml
charts/orb/templates/users-deployment.yaml
charts/orb/values.yaml

This PR is permiting jaeger host selection.

[FIX] permitting jaeger host selection using variables

---

charts/orb/Chart.yaml

This PR bump version to release.

bump version to release

---

charts/orb/templates/ingress.yaml
charts/orb/values.yaml

This PR fix annotations separated on two nginx ingress.

[FIX] two annotations for two ingress

---

charts/orb/Chart.yaml
charts/orb/templates/ingress.yaml
charts/orb/values.yaml

New version release

---

charts/orb/Chart.yaml
charts/orb/templates/adapter_mqtt-statefulstet.yaml
charts/orb/templates/ingress.yaml
charts/orb/values.yaml

This PR changes:
- Fix variable name on ingress annotations
- Add max_message_rate = 5 on Vernemq

[FIX] add rate message on mqtt

---

charts/orb/templates/adapter_mqtt-statefulstet.yaml

This PR is changing max_message_rate from 5 to 10

[FIX] increase max_message_rate

---

charts/orb/Chart.yaml
charts/orb/templates/adapter_mqtt-statefulstet.yaml

Bump version

---

charts/orb/Chart.yaml
charts/orb/templates/migrate-job.yaml
charts/orb/values.yaml

This PR fix the error when we disable auto migrate flag, and a error when re-sync this helm chart by ArgoCD because needs to force sync to perform properly

[FIX] add end on if auto migrate

---

KIND.md

Improved `KIND.md` to be more friendly for developers that are not usual to `docker/k8s` tools.

Improve KIND.md

---

charts/orb/Chart.yaml
charts/orb/README.md
charts/orb/templates/auth-deployment.yaml
charts/orb/templates/fleet-deployment.yaml
charts/orb/templates/migrate-job.yaml
charts/orb/templates/policies-deployment.yaml
charts/orb/templates/sinks-deployment.yaml
charts/orb/templates/things-deployment.yaml
charts/orb/templates/users-deployment.yaml
charts/orb/values.yaml

This PR permit use all database and email credentials as k8s secrets

[FIX] secure credentials as k8s secrets

---

charts/orb/Chart.yaml
charts/orb/templates/users-deployment.yaml

This PR fixes the smtp to helm chart use k8s secrets as smtp credentials

Fix smtp condition

---

charts/orb/Chart.yaml
charts/orb/charts/nats/templates/configmap.yaml

This PR add cluster name on nats-conf file

[FIX] nats cluster name

---

charts/orb/Chart.yaml
charts/orb/templates/sinker-otel-deployment.yaml
charts/orb/templates/sinker-otel-service.yaml
charts/orb/values.yaml

This PR add OTEL parameters in a new sinker deployment

[Feat] Add OTEL params

---

charts/orb/Chart.yaml
charts/orb/templates/maestro-deployment.yaml
charts/orb/templates/maestro-service-account.yaml
charts/orb/templates/maestro-service.yaml
charts/orb/templates/sinker-otel-deployment.yaml
charts/orb/values.yaml

This PR changes:
- Added Orb maestro micro service manifests

Add Orb maestro micro service

---

charts/orb/Chart.yaml
charts/orb/templates/maestro-deployment.yaml

Permit individual replicas for maestro service

[Feat] Permit individual replicas for maestro service

---

charts/orb/Chart.yaml
charts/orb/templates/maestro-deployment.yaml

[Fix] sinks grpc host on maestro

[Fix] sinks grpc host on maestro

---

charts/orb/Chart.yaml
charts/orb/values.yaml

Fix for wildcard certificate use

Set default values for ingress

---

charts/orb/Chart.yaml
charts/orb/templates/users-deployment.yaml
charts/orb/values.yaml

This PR changes:
- recovery password endpoint as variables to permit be injected

Fix resetPasswordEndpoint as variable to be injected

---

charts/orb/Chart.yaml
charts/orb/templates/maestro-service-account.yaml
charts/orb/values.yaml

This PR add support for RoleBinding to give access to maestro micro service into the k8s cluster

[ORB-276] Fix maestro rbac

---

charts/orb/templates/fleet-deployment.yaml
charts/orb/templates/policies-deployment.yaml
charts/orb/templates/sinker-deployment.yaml
charts/orb/templates/sinks-deployment.yaml
charts/orb/templates/things-deployment.yaml

added dlv port in orb deployment

added dlv port in orb deployment

---

charts/orb/Chart.yaml
charts/orb/templates/ingress.yaml

feat(ingress): add sinks new api to ingress.

---

charts/orb/Chart.yaml
charts/orb/templates/ingress.yaml

fix new sinks endpoint
